import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import Layout from '../components/Layout';
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle, 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow,
  Button,
  Input,
  Badge,
  Alert,
  AlertDescription
} from '../components/ui-components';
import { 
  Search, 
  BarChart3, 
  Trash2, 
  Eye, 
  RefreshCw,
  TrendingUp,
  User
} from 'lucide-react';
import { analyticsAPI } from '../api/admin';
import { toast } from 'sonner';
import { format } from 'date-fns';

const AnalyticsManagement = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [searchUserId, setSearchUserId] = useState('');
  const queryClient = useQueryClient();
  
  const { data: analyticsData, isLoading, error, refetch } = useQuery({
    queryKey: ['analytics', currentPage, searchUserId],
    queryFn: () => analyticsAPI.getAllAnalytics(currentPage, 10, searchUserId || null),
    keepPreviousData: true,
    onError: (error) => {
      console.error('Analytics fetch error:', error);
      toast.error('Failed to load analytics data');
    }
  });

  const { data: statsData } = useQuery({
    queryKey: ['analytics-stats'],
    queryFn: analyticsAPI.getAnalyticsStats,
    onError: (error) => {
      console.error('Analytics stats fetch error:', error);
    }
  });

  const deleteAnalyticsMutation = useMutation({
    mutationFn: analyticsAPI.deleteAnalytics,
    onSuccess: () => {
      toast.success('Analytics deleted successfully');
      queryClient.invalidateQueries(['analytics']);
      queryClient.invalidateQueries(['analytics-stats']);
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Failed to delete analytics');
    }
  });

  const handleDeleteAnalytics = async (analyticsId) => {
    if (window.confirm('Are you sure you want to delete this analytics record? This action cannot be undone.')) {
      deleteAnalyticsMutation.mutate(analyticsId);
    }
  };

  const handleSearch = (e) => {
    e.preventDefault();
    setCurrentPage(1);
    refetch();
  };

  const analytics = analyticsData?.data?.analytics || [];
  const totalPages = analyticsData?.data?.totalPages || 1;
  const totalAnalytics = analyticsData?.data?.totalAnalytics || 0;
  const stats = statsData?.data || {};

  if (error) {
    return (
      <Layout>
        <div className="space-y-6">
          <h1 className="text-3xl font-bold text-gray-900">Analytics Management</h1>
          <Alert variant="destructive">
            <AlertDescription>
              Failed to load analytics data. Please try again later.
            </AlertDescription>
          </Alert>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Analytics Management</h1>
            <p className="text-gray-600 mt-1">
              Monitor and manage data analytics generated by users
            </p>
          </div>
          <Button 
            variant="outline" 
            onClick={() => refetch()}
            disabled={isLoading}
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
        </div>

        {/* Stats Cards */}
        <div className="grid gap-4 md:grid-cols-4">
          <Card className="admin-stats-card">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Total Analytics
              </CardTitle>
              <BarChart3 className="h-4 w-4 text-blue-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">
                {stats.totalAnalytics?.toLocaleString() || totalAnalytics.toLocaleString()}
              </div>
              <p className="text-xs text-gray-500 mt-1">
                All time generated
              </p>
            </CardContent>
          </Card>

          <Card className="admin-stats-card">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                This Month
              </CardTitle>
              <TrendingUp className="h-4 w-4 text-green-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">
                {stats.analyticsThisMonth?.toLocaleString() || '0'}
              </div>
              <p className="text-xs text-gray-500 mt-1">
                +{stats.growthPercentage || 0}% from last month
              </p>
            </CardContent>
          </Card>

          <Card className="admin-stats-card">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Today
              </CardTitle>
              <BarChart3 className="h-4 w-4 text-purple-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">
                {stats.analyticsToday || '0'}
              </div>
              <p className="text-xs text-gray-500 mt-1">
                Generated today
              </p>
            </CardContent>
          </Card>

          <Card className="admin-stats-card">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">
                Avg per User
              </CardTitle>
              <User className="h-4 w-4 text-orange-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-gray-900">
                {stats.avgAnalyticsPerUser?.toFixed(1) || '0.0'}
              </div>
              <p className="text-xs text-gray-500 mt-1">
                Analytics per user
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Search and Filters */}
        <Card className="admin-card">
          <CardHeader>
            <CardTitle className="text-lg font-semibold text-gray-900">
              Search Analytics
            </CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSearch} className="flex space-x-4">
              <div className="flex-1">
                <Input
                  placeholder="Search by User ID..."
                  value={searchUserId}
                  onChange={(e) => setSearchUserId(e.target.value)}
                  className="w-full"
                />
              </div>
              <Button type="submit" variant="admin">
                <Search className="h-4 w-4 mr-2" />
                Search
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Analytics Table */}
        <Card className="admin-card">
          <CardHeader>
            <CardTitle className="text-lg font-semibold text-gray-900">
              Analytics Records
            </CardTitle>
            <CardDescription>
              {totalAnalytics} total analytics found
            </CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="space-y-4">
                {[...Array(5)].map((_, i) => (
                  <div key={i} className="flex space-x-4 animate-pulse">
                    <div className="w-12 h-12 bg-gray-200 rounded"></div>
                    <div className="flex-1 space-y-2">
                      <div className="h-4 bg-gray-200 rounded w-1/4"></div>
                      <div className="h-3 bg-gray-200 rounded w-1/2"></div>
                    </div>
                  </div>
                ))}
              </div>
            ) : analytics.length === 0 ? (
              <div className="text-center py-8">
                <BarChart3 className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                <p className="text-gray-500">No analytics found</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Analytics ID</TableHead>
                      <TableHead>User</TableHead>
                      <TableHead>File</TableHead>
                      <TableHead>Insights</TableHead>
                      <TableHead>Preview Data</TableHead>
                      <TableHead>Created</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {analytics.map((analytic) => (
                      <TableRow key={analytic._id}>
                        <TableCell>
                          <div className="flex items-center space-x-2">
                            <BarChart3 className="h-4 w-4 text-blue-600" />
                            <span className="font-mono text-sm">
                              {analytic._id.slice(-8)}
                            </span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm text-gray-900">
                            {analytic.userId?.email || 'Unknown User'}
                          </div>
                          <div className="text-xs text-gray-500">
                            ID: {analytic.userId?._id?.slice(-8) || 'N/A'}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm text-gray-900">
                            {analytic.fileId?.filename || 'Unknown File'}
                          </div>
                          <div className="text-xs text-gray-500">
                            ID: {analytic.fileId?._id?.slice(-8) || 'N/A'}
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="secondary">
                            {analytic.insights?.length || 0} insights
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">
                            {analytic.preview?.length || 0} rows
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm text-gray-900">
                            {format(new Date(analytic.createdAt), 'MMM dd, yyyy')}
                          </div>
                          <div className="text-xs text-gray-500">
                            {format(new Date(analytic.createdAt), 'HH:mm')}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex space-x-2">
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => {
                                // View analytics details - could open a modal
                                console.log('View analytics:', analytic);
                                toast.info('Analytics details view - feature coming soon');
                              }}
                            >
                              <Eye className="h-3 w-3" />
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => handleDeleteAnalytics(analytic._id)}
                              disabled={deleteAnalyticsMutation.isLoading}
                            >
                              <Trash2 className="h-3 w-3" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}

            {/* Pagination */}
            {totalPages > 1 && (
              <div className="flex items-center justify-between mt-6">
                <p className="text-sm text-gray-700">
                  Page {currentPage} of {totalPages}
                </p>
                <div className="flex space-x-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                    disabled={currentPage === 1}
                  >
                    Previous
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                    disabled={currentPage === totalPages}
                  >
                    Next
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
};

export default AnalyticsManagement;
